### ISSUE TITLE
[Feature] Recurrent events

### ISSUE THREAD

**Issue by arcanedev-maroc** [danieltoorani/adminScheduler#2]
I don't know if the fullcalendar supports the recurrent events or not.

But the most requested/missed feature is **recurrent events**.

There are some tools/solutions for this feature:

  * https://github.com/jakubroztocil/rrule
  * https://github.com/simshaun/recurr (PHP)
  * https://www.textmagic.com/free-tools/rrule-generator
  * https://tools.ietf.org/html/rfc2445#section-4.8.2

Keep up the good work 👍

**Comment by danieltoorani** [comment]
Thanks arcanedev, those are some good solutions!
